### ISSUE TITLE
Similar setup for RHEL distribution?

### ISSUE THREAD

**Issue by alepodj** [fnep/fastapi_behind_apache_using_wsgi#1]
Hi

This is not really an issue but sort of a request.

Ive been trying to mimic this setup of running FastAPI with wsgi in a RHEL environment, have u setup or have the steps to do so, minus the container really?

Specially this lib: `libapache2-mod-wsgi-py3` for Ubuntu, is not in RHEL, what i got is:

```
mod_wsgi.x86_64
python2-mod_wsgi.x86_64
python3-mod_wsgi.x86_64
```

**Comment by fnep** [comment]
Hi, no problem. I just added an example based on UBI, what should work on RHEL i hope.  See `Dockerfile.redhat`.
